### ISSUE TITLE
Document how to debug the kernel with gdb/vdb

### ISSUE THREAD

**Issue by melkyades** [powerlang/powerlang#59]
How to run it, typical commands, etc

**Comment by melkyades** [comment]
btw, now running `gdb --args ./bee-dmr bee-dmr.bsl` in `build/x86_64-linux` gives me:

```
Reading symbols from ./bee-dmr...
Traceback (most recent call last):
  File "/powerlang/build/x86_64-linux/bee-dmr-gdb.py", line 14, in <module>
    from powerlang import *
  File "/powerlang/debug/powerlang/__init__.py", line 12, in <module>
    import powerlang.printing
  File "/powerlang/debug/powerlang/printing.py", line 20, in <module>
    from  vdb.printing import CxxCollectionPrettyPrinter
ModuleNotFoundError: No module named 'vdb'
(gdb) ```

**Comment by janvrany** [comment]
Yeah, my fault, I forgot I use some common code from VDB. Worse that that, that common code is not pushed. Sorry.
Working on this right now.

**Comment by janvrany** [comment]
Just created a draft PR #60 to address this.

**Comment by melkyades** [comment]
I now get the following error

```
Reading symbols from ./bee-dmr...
Traceback (most recent call last):
  File "/home/pocho/data/proyectos/powerlang-metaphysics/build/x86_64-linux/bee-dmr-gdb.py", line 14, in <module>
    from powerlang import *
  File "/home/pocho/data/proyectos/powerlang-metaphysics/debug/powerlang/__init__.py", line 12, in <module>
    import powerlang.printing
  File "/home/pocho/data/proyectos/powerlang-metaphysics/debug/powerlang/printing.py", line 20, in <module>
    from  vdb.printing import CxxCollectionPrettyPrinter
  File "/home/pocho/data/proyectos/powerlang-metaphysics/debug/jv-vdb/python/vdb/__init__.py", line 344, in <module>
    def _var_create(argv):
  File "/home/pocho/data/proyectos/powerlang-metaphysics/debug/jv-vdb/python/vdb/__init__.py", line 331, in _command
    class _Command(gdb.MICommand):
AttributeError: module 'gdb' has no attribute 'MICommand'
```

`GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2`, is that an old gdb?

**Comment by janvrany** [comment]
Yeah, for now you need patched GDB, see https://swing.fit.cvut.cz/hg/jv-libgdbs/file/tip/doc/GDB.md

**Comment by shingarov** [comment]
I'd call it "GDB from jv's tree", because it doesn't involve any specific patching step: just clone, configure and make.  I've set my origin to point to github:janvrany/binutils-gdb on the eve of the Hackathon and been treating it as if it were sourceware/master, even when working on things unrelated to libgdbs/vdb (such as testing gem5's compatibility with gdb) and it never caused me any trouble.
